### ISSUE TITLE
Build failure on Mac

### ISSUE THREAD

**Issue by fionser** [zama-ai/concrete-ntt#3]
cargo --version 
`cargo 1.69.0 (6e9a83356 2023-04-12)`

<img width="621" alt="截屏2023-04-28 13 26 03" src="https://user-images.githubusercontent.com/1809457/235061623-91f9f824-077c-4baa-9420-195ea0a98a65.png">

**Comment by IceTDrinker** [comment]
hello, do you have an x86 or Apple Silicon mac ?

**Comment by fionser** [comment]
yes, I built on a Apple Silicon (M2)

**Comment by IceTDrinker** [comment]
thank you, we indeed see the problem, we'll work to fix it!

**Comment by IceTDrinker** [comment]
fixed in https://github.com/zama-ai/concrete-ntt/pull/5 let us know if you are still experiencing issues.
