### ISSUE TITLE
Question on Barrett 

### ISSUE THREAD

**Issue by fionser** [zama-ai/concrete-ntt#8]
Given a prime modulus `p ~ 2^q`, why we compute the barrett pre-conditioner using `2^{q + max_bits}/q` instead of
using `2^{2 * max_bits} / q` ?

For example, for the non-AVX implementation, we can store the barrett as `2^{2*64}/q` so that we can lazy reduce a value 
in [0, 2^{128}) back to [0, q) (which the `Div64` trait seems do the same thing)

**Comment by sarah-ek** [comment]
if the modulus is less than `2^{max_bits - 1}`, then `2^{2 * max_bits} / q` doesn't fit in an integer of size `max_bits`

and if the modulus is larger, then i don't think barrett can work because it returns a result in `[0, 2 * q)`, which can overflow

**Comment by IceTDrinker** [comment]
hello @fionser if your question has been answered we will close this issue, do you have everything you need ?
